# Generated by Django 4.0.4 on 2022-05-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_total_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_rate',
        ),
    ]
