# Generated by Django 4.0.4 on 2022-05-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_wishlist_product_wishlist_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_total_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
