# Generated by Django 4.0.4 on 2022-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cart_cart_total_price_remove_cartitem_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
    ]
